baseurl = "http://yoichitgy.github.io/"
languageCode = "en-us"
title = "Swift Injection"
theme = "angels-ladder"
disqusShortname = "yoichitgy"

[Params]
subtitle = "Swift patterns and practices"
github = "https://github.com/yoichitgy"
copyright = "Â© 2015 Yoichi Tagaya. All rights reserved."
analytics = "UA-66106661-1"
